# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d2e7baa39388e4a4d4a9fcfcca475eeb3c2ba31d5adcd9bf6c92b315cff88539936b72b5ba03351aef2eb1f8fc8164e604d45a98e06baf38fd7e12267a3e3c5

test:
  secret_key_base: f60da134118c86373bb3c62dc3626850769d5f1a4381e55a7607b17cbb77c4e15b73a8fe06781d3e3d767d5bb0e3580b597730b276d899a87c87342e1e67ff89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
