class Cell < ApplicationRecord
  belongs_to :drug_1, class_name: 'Drug'
  belongs_to :drug_2, class_name: 'Drug'
  belongs_to :categorization
  
  # For reference:
  # Cell.where(drug_1_id: 2, drug_2_id: 1).or(Cell.where(drug_1_id: 1, drug_2_id: 2))
  
  def self.setup_cells
    Cell.setup_lsd_cells
  end
  
  def self.setup_lsd_cells
    lsd = Drug.find_by(name: 'LSD')
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Mushrooms'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'DMT'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Mescaline'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'DOx'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'NBOMes'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: '2C-x'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: '2C-T-x'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: '5-MeO-xxT'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Cannabis'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Ketamine'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'MXE'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'DXM'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Nitrous'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Amphetamines'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'MDMA'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Cocaine'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Caffeine'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Alcohol'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'GHB/GBL'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Opioids'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Tramadol'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'Benzodiazepines'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'MAOIs'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: lsd, drug_2: Drug.find_by(name: 'SSRIs'), categorization: Categorization.find_by(scale: 3))
  end
  
  def self.setup_mushrooms_cells
    mushrooms = Drug.find_by(name: 'Mushrooms')
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'DMT'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'Mescaline'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'DOx'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'NBOMes'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: '2C-x'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: '2C-T-x'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: '5-MeO-xxT'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'Cannabis'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'Ketamine'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'MXE'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'DXM'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'Nitrous'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'Amphetamines'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'MDMA'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'Cocaine'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'Caffeine'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'Alcohol'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'GHB/GBL'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'Opioids'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'Tramadol'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'Benzodiazepines'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'MAOIs'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mushrooms, drug_2: Drug.find_by(name: 'SSRIs'), categorization: Categorization.find_by(scale: 3))
  end
  
  def self.setup_dmt_cells
    dmt = Drug.find_by(name: 'DMT')
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'Mescaline'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'DOx'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'NBOMes'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: '2C-x'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: '2C-T-x'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: '5-MeO-xxT'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'Cannabis'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'Ketamine'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'MXE'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'DXM'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'Nitrous'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'Amphetamines'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'MDMA'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'Cocaine'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'Caffeine'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'Alcohol'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'GHB/GBL'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'Opioids'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'Tramadol'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'Benzodiazepines'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'MAOIs'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dmt, drug_2: Drug.find_by(name: 'SSRIs'), categorization: Categorization.find_by(scale: 3))
  end
  
  def self.setup_mescaline_cells
    mescaline = Drug.find_by(name: 'Mescaline')
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'DOx'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'NBOMes'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: '2C-x'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: '2C-T-x'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: '5-MeO-xxT'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'Cannabis'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'Ketamine'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'MXE'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'DXM'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'Nitrous'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'Amphetamines'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'MDMA'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'Cocaine'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'Caffeine'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'Alcohol'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'GHB/GBL'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'Opioids'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'Tramadol'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'Benzodiazepines'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'MAOIs'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: mescaline, drug_2: Drug.find_by(name: 'SSRIs'), categorization: Categorization.find_by(scale: 3))
  end
  
  def self.setup_dox_cells
    dox = Drug.find_by(name: 'DOx')
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'NBOMes'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: '2C-x'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: '2C-T-x'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: '5-MeO-xxT'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'Cannabis'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'Ketamine'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'MXE'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'DXM'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'Nitrous'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'Amphetamines'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'MDMA'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'Cocaine'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'Caffeine'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'Alcohol'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'GHB/GBL'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'Opioids'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'Tramadol'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'Benzodiazepines'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'MAOIs'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: dox, drug_2: Drug.find_by(name: 'SSRIs'), categorization: Categorization.find_by(scale: 3))
  end
  
  def self.setup_nbomes_cells
    nbomes = Drug.find_by(name: 'NBOMes')
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: '2C-x'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: '2C-T-x'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: '5-MeO-xxT'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'Cannabis'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'Ketamine'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'MXE'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'DXM'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'Nitrous'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'Amphetamines'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'MDMA'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'Cocaine'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'Caffeine'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'Alcohol'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'GHB/GBL'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'Opioids'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'Tramadol'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'Benzodiazepines'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'MAOIs'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: nbomes, drug_2: Drug.find_by(name: 'SSRIs'), categorization: Categorization.find_by(scale: 3))
  end
  
  def self.setup_2cx_cells
    2cx = Drug.find_by(name: '2C-x')
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: '2C-T-x'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: '5-MeO-xxT'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'Cannabis'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'Ketamine'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'MXE'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'DXM'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'Nitrous'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'Amphetamines'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'MDMA'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'Cocaine'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'Caffeine'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'Alcohol'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'GHB/GBL'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'Opioids'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'Tramadol'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'Benzodiazepines'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'MAOIs'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 2cx, drug_2: Drug.find_by(name: 'SSRIs'), categorization: Categorization.find_by(scale: 3))
  end
  
  def self.setup_2ctx_cells
    2ctx = Drug.find_by(name: '2C-T-x')
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: '5-MeO-xxT'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'Cannabis'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'Ketamine'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'MXE'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'DXM'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'Nitrous'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'Amphetamines'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'MDMA'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'Cocaine'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'Caffeine'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'Alcohol'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'GHB/GBL'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'Opioids'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'Tramadol'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'Benzodiazepines'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'MAOIs'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 2ctx, drug_2: Drug.find_by(name: 'SSRIs'), categorization: Categorization.find_by(scale: 3))
  end
  
  def self.setup_5me0xxt_cells
    5me0xxt = Drug.find_by(name: '5-MeO-xxT')
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'Cannabis'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'Ketamine'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'MXE'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'DXM'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'Nitrous'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'Amphetamines'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'MDMA'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'Cocaine'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'Caffeine'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'Alcohol'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'GHB/GBL'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'Opioids'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'Tramadol'), categorization: Categorization.find_by(scale: 5))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'Benzodiazepines'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'MAOIs'), categorization: Categorization.find_by(scale: 6))
    Cell.create!(drug_1: 5me0xxt, drug_2: Drug.find_by(name: 'SSRIs'), categorization: Categorization.find_by(scale: 3))
  end
  
  def self.setup_cannabis_cells
    cannabis = Drug.find_by(name: 'Cannabis')
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'Ketamine'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'MXE'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'DXM'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'Nitrous'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'Amphetamines'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'MDMA'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'Cocaine'), categorization: Categorization.find_by(scale: 4))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'Caffeine'), categorization: Categorization.find_by(scale: 2))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'Alcohol'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'GHB/GBL'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'Opioids'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'Tramadol'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'Benzodiazepines'), categorization: Categorization.find_by(scale: 3))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'MAOIs'), categorization: Categorization.find_by(scale: 1))
    Cell.create!(drug_1: cannabis, drug_2: Drug.find_by(name: 'SSRIs'), categorization: Categorization.find_by(scale: 2))
  end
  
end
